In [1]:
import pandas as pd
import numpy as np

In [2]:
# giving the column names to the datset

columns=[
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

In [4]:
# adult.data dataset in the train_df

train_df=pd.read_csv(
    "C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\Adult_Income_Data_Cleaning_and_EDA\\data\\adult.data",
    names=columns,
    sep=",",
    skipinitialspace=True
)

train_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
print(train_df.shape)

(32561, 15)

In [5]:
# adult.test dataset in the test_df

test_df=pd.read_csv(
    "C:\\Users\\vaish\\OneDrive\\Documents\\DATA SCIENCE COURSE\\Projects\\Adult_Income_Data_Cleaning_and_EDA\\data\\adult.data",
    names=columns,
    sep=",",
    skipinitialspace=True,
    skiprows=1
)

test_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [6]:
# # converting the tarin_df and test_df into train and test

# train_df["source_split"]="train"
# test_df["source_split"]="test"
# df

In [7]:
# now concat both of them

df=pd.concat(
    [train_df,test_df],
    ignore_index=True
)

In [8]:
print(df.shape)

(65121, 15)

In [9]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [10]:
df.shape

(65121, 15)

In [11]:
df.dtypes

age               int64
workclass           str
fnlwgt            int64
education           str
education_num     int64
marital_status      str
occupation          str
relationship        str
race                str
sex                 str
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country      str
income              str
dtype: object

In [12]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,65121.000000,6.512100e+04,65121.000000,65121.000000,65121.000000,65121.000000
mean,38.581640,1.897801e+05,10.080635,1077.632008,87.305170,40.437463
std,13.640432,1.055491e+05,2.572695,7385.290835,402.960073,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [13]:
# Removing the leading and trailing spaces from all the catogrical columns

columns_cat=df.select_dtypes(include="object").columns

for col in columns_cat:
    df[col]=df[col].str.strip()

C:\Users\vaish\AppData\Local\Temp\ipykernel_22688\2682539964.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns_cat=df.select_dtypes(include="object").columns

In [14]:
# contains ? in place of the unknown values

df=df.replace("?",np.nan)

In [15]:
df.isnull().sum()

age                  0
workclass         3672
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        3686
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country    1166
income               0
dtype: int64

In [16]:
missing_values=pd.DataFrame(
    {
        "Missing_Count": df.isnull().sum(),
        "Missing_Percentage":df.isnull().mean()*100
    }
)
missing_values=missing_values[missing_values["Missing_Count"]>0]

print(missing_values)

                Missing_Count  Missing_Percentage
workclass                3672            5.638734
occupation               3686            5.660232
native_country           1166            1.790513

In [17]:
# filling the missing values with unknown
missing_cat=[
    "workclass",
    "occupation",
    "native_country"
]

for i in missing_cat:
    df[i]=df[i].fillna("Unknown")

df[missing_cat].isnull().sum()

workclass         0
occupation        0
native_country    0
dtype: int64

In [18]:
# income Column

df["income"]=df["income"].replace(".","",regex=False)

In [19]:
# filtering out the higher income than 50k

df["high_income"]=(df["income"]==">50K").astype(int)

df[["income", "high_income"]].head(10)

  income  high_income
0  <=50K            0
1  <=50K            0
2  <=50K            0
3  <=50K            0
4  <=50K            0
5  <=50K            0
6  <=50K            0
7   >50K            1
8   >50K            1
9   >50K            1

In [20]:
# numerical columns

numeric_col=[
    "age",
    "fnlwgt",
    "education_num",
    "capital_gain",
    "capital_loss",
    "hours_per_week"
]

for i in numeric_col:
    df[i]=pd.to_numeric(df[i],errors="coerce")

df[numeric_col].dtypes
df[numeric_col].isnull().sum()
df[numeric_col].duplicated().sum()

np.int64(32787)

In [21]:
# creating the different age groups

df["age_group"]=pd.cut(df["age"],
                       bins=[1,25,35,45,55,65,100],
                       labels=["18-25",'26-35','36-45','46-55','56-65','66+'])

df['age_group'].value_counts()

age_group
26-35    17028
36-45    16017
18-25    12822
46-55    11076
56-65     5862
66+       2316
Name: count, dtype: int64

In [22]:
# creating the different working hour groups

df["hour_group"]=pd.cut(df["hours_per_week"],
                        bins=[0,20,40,60,150],
                        labels=['0-20','21-40','41-60','61+']
)


df["hour_group"].value_counts()

hour_group
21-40    40103
41-60    16942
0-20      5856
61+       2220
Name: count, dtype: int64

In [23]:
# creating the net capital column from capital gain and captial loss

df["net_capital"]=(df["capital_gain"]-df["capital_loss"])

df[["capital_gain","capital_loss","net_capital"]].head()

   capital_gain  capital_loss  net_capital
0          2174             0         2174
1             0             0            0
2             0             0            0
3             0             0            0
4             0             0            0

In [24]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
high_income       0
age_group         0
hour_group        0
net_capital       0
dtype: int64

In [25]:
# final inspection of the dataset

print("Shape: ",df.shape)

print("Columns: ",df.columns)

print("Data Types: ",df.dtypes)

print("Duplicated: ",df.duplicated().sum())

Shape:  (65121, 19)
Columns:  Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income', 'high_income', 'age_group', 'hour_group', 'net_capital'],
      dtype='str')
Data Types:  age                  int64
workclass              str
fnlwgt               int64
education              str
education_num        int64
marital_status         str
occupation             str
relationship           str
race                   str
sex                    str
capital_gain         int64
capital_loss         int64
hours_per_week       int64
native_country         str
income                 str
high_income          int64
age_group         category
hour_group        category
net_capital          int64
dtype: object
Duplicated:  32584

In [26]:
df.columns=df.columns.str.strip().str.title()

In [27]:
df["Workclass"].unique()
df["Education"].unique()
df["Marital_Status"].unique()
df["Occupation"].unique()
df["Relationship"].unique()
df["Race"].unique()
df["Sex"].unique()
df["Native_Country"].unique()

<StringArray>
[             'United-States',                       'Cuba',
                    'Jamaica',                      'India',
                    'Unknown',                     'Mexico',
                      'South',                'Puerto-Rico',
                   'Honduras',                    'England',
                     'Canada',                    'Germany',
                       'Iran',                'Philippines',
                      'Italy',                     'Poland',
                   'Columbia',                   'Cambodia',
                   'Thailand',                    'Ecuador',
                       'Laos',                     'Taiwan',
                      'Haiti',                   'Portugal',
         'Dominican-Republic',                'El-Salvador',
                     'France',                  'Guatemala',
                      'China',                      'Japan',
                 'Yugoslavia',                       'Peru',
 'Outlying-US(Guam-USVI-etc)',                   'Scotland',
            'Trinadad&Tobago',                     'Greece',
                  'Nicaragua',                    'Vietnam',
                       'Hong',                    'Ireland',
                    'Hungary',         'Holand-Netherlands']
Length: 42, dtype: str

In [28]:
df

,Age,Workclass,Fnlwgt,Education,Education_Num,Marital_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_Per_Week,Native_Country,Income,High_Income,Age_Group,Hour_Group,Net_Capital
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0,36-45,21-40,2174
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0,46-55,0-20,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0,36-45,21-40,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0,46-55,21-40,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0,26-35,21-40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65116,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,0,26-35,21-40,0
65117,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,1,36-45,21-40,0
65118,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,0,56-65,21-40,0
65119,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,0,18-25,0-20,0
65120,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,1,46-55,21-40,15024

In [29]:
df.to_csv("adult_income.csv",index=False)